const state={key:sessionStorage.getItem('noon_admin_key')||'',leads:[],type:'all',status:'all',search:''};
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(path,opts={}){const headers={...(opts.headers||{}),'Content-Type':'application/json'};if(state.key)headers.Authorization=`Bearer ${state.key}`;const r=await fetch(path,{...opts,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
function loginView(authed){$('#loginPanel').hidden=authed;$('#dashboard').hidden=!authed}
function metrics(){const l=state.leads;$('#mTotal').textContent=l.length;$('#mNew').textContent=l.filter(x=>x.status==='new').length;$('#mQualified').textContent=l.filter(x=>x.status==='qualified').length;$('#mStrategic').textContent=l.filter(x=>['partner','investor'].includes(x.lead_type)).length}
function filtered(){return state.leads.filter(l=>(state.type==='all'||l.lead_type===state.type)&&(state.status==='all'||l.status===state.status)&&(!state.search||[l.name,l.email,l.company,l.country,l.interest,l.message].some(v=>String(v||'').toLowerCase().includes(state.search))))}
function render(){metrics();const rows=filtered();$('#leadRows').innerHTML=rows.map(l=>`<tr><td><span class="badge">${esc(l.lead_type)}</span></td><td><strong>${esc(l.name)}</strong><br><small>${esc(l.email)}</small></td><td>${esc(l.company||'—')}</td><td>${esc(l.country||'—')}</td><td><span class="badge">${esc(l.status)}</span></td><td>${new Date(l.created_at).toLocaleString()}</td><td><button class="row-action" data-id="${esc(l.id)}">Open</button></td></tr>`).join('');$('#empty').hidden=rows.length>0;document.querySelectorAll('.row-action').forEach(b=>b.onclick=()=>openLead(b.dataset.id))}
async function load(){try{const d=await api('/api/leads');state.leads=d.leads||[];loginView(true);render()}catch(e){loginView(false);$('#loginMsg').textContent=e.message==='Unauthorized'?'Invalid admin key or ADMIN_API_KEY is not configured.':e.message}}
function openLead(id){const l=state.leads.find(x=>x.id===id);if(!l)return;$('#leadDetail').innerHTML=`<h2>${esc(l.name)}</h2><p><span class="badge">${esc(l.lead_type)}</span> <span class="badge">${esc(l.status)}</span></p><div class="detail-grid"><div class="detail-card"><small>Email</small>${esc(l.email)}</div><div class="detail-card"><small>Phone</small>${esc(l.phone||'—')}</div><div class="detail-card"><small>Company</small>${esc(l.company||'—')}</div><div class="detail-card"><small>Country</small>${esc(l.country||'—')}</div><div class="detail-card"><small>Interest</small>${esc(l.interest||'—')}</div><div class="detail-card"><small>Received</small>${new Date(l.created_at).toLocaleString()}</div></div><div class="detail-card" style="margin-top:14px"><small>Message</small><div class="detail-message">${esc(l.message||'No message provided.')}</div></div><div class="detail-actions">${['new','contacted','qualified','closed','rejected'].map(s=>`<button data-status="${s}" data-id="${esc(l.id)}">Mark ${s}</button>`).join('')}</div>`;$('#leadDetail').querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/api/lead-status',{method:'PATCH',body:JSON.stringify({id:b.dataset.id,status:b.dataset.status})});await load();$('#leadDialog').close()}catch(e){alert(e.message)}finally{b.disabled=false}});$('#leadDialog').showModal()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();state.key=$('#adminKey').value.trim();sessionStorage.setItem('noon_admin_key',state.key);$('#loginMsg').textContent='';await load()};$('#logout').onclick=()=>{sessionStorage.removeItem('noon_admin_key');state.key='';state.leads=[];loginView(false)};$('#refresh').onclick=load;$('#search').oninput=e=>{state.search=e.target.value.toLowerCase().trim();render()};$('#statusFilter').onchange=e=>{state.status=e.target.value;render()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.type=b.dataset.filter;render()});if(state.key)load();else loginView(false);
